example/things/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.ThingList.as_view(), name='list'),
    url(r'^new/$', views.ThingCreate.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.ThingDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.ThingUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', views.ThingDelete.as_view(), name='delete'),
]

example/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin


admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html')),
    url(r'^things/', include('example.things.urls', namespace='things')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

example/things/models.py
from django.urls import reverse
from django.db import models


class Thing(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('things:detail', args=[str(self.id)])

example/things/forms.py
from django import forms
from .models import Thing


class ThingForm(forms.ModelForm):
    class Meta:
        model = Thing
        fields = ['name', ]

example/things/views.py
from django.urls import reverse_lazy
from vanilla import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import ThingForm
from .models import Thing


class ThingList(ListView):
    model = Thing
    paginate_by = 20


class ThingCreate(CreateView):
    model = Thing
    form_class = ThingForm
    success_url = reverse_lazy('things:list')


class ThingDetail(DetailView):
    model = Thing


class ThingUpdate(UpdateView):
    model = Thing
    form_class = ThingForm
    success_url = reverse_lazy('things:list')


class ThingDelete(DeleteView):
    model = Thing
    success_url = reverse_lazy('things:list')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap -->
        <link href="{% static "bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "bootstrap/dist/css/bootstrap-theme.min.css" %}" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        {% block extra_head %}
        {% endblock %}
    </head>
    <body>
        <div class="navbar navbar-inverse" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Example</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'things:list' %}">List</a></li>
                <li><a href="{% url 'things:create' %}">Create</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
        <div class="container">
            <h1>{% block heading %}{% endblock %}</h1>
            {% block content %}
            {% endblock %}
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>

        {% block extra_script %}
        {% endblock %}
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block heading %}Home{% endblock %}

{% block content %}
{% endblock content %}

templates/things/thing_confirm_delete.html
{% extends "base.html" %}

{% block heading %}Delete{% endblock %}

{% block content %}
    <p>Are you sure you want to delete?</p>

    <form id="thing_form" method="post" action=".">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-primary" /> <a href="{% url 'things:list' %}" class="btn btn-danger">No</a>
    </form>
{% endblock %}

templates/things/thing_detail.html
{% extends "base.html" %}

{% block heading %}Detail{% endblock %}

{% block content %}
    <p>{{ object.name }}</p>
    <a href="{% url 'things:list' %}">List</a>
{% endblock %}

templates/things/thing_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block heading %}Create / Update{% endblock %}

{% block content %}
    <form id="thing_form" method="post" action="." class="form">
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
      {% endbuttons %}
    </form>
{% endblock %}

templates/things/thing_list.html
{% extends "base.html" %}

{% block heading %}Listing{% endblock %}

{% block content %}
    <table class="table">
    {% for object in object_list %}
    <tr>
        <td>{{ object }}</td>
        <td><a href="{{ object.get_absolute_url }}">Details</a></td>
        <td><a href="{% url 'things:update' object.pk %}">Update</a></td>
        <td><a href="{% url 'things:delete' object.pk %}">Delete</a></td>
    </tr>
    {% empty %}
    <tr>
        <td><p>No items.</p></td>
    </tr>
    {% endfor %}
    </table>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'things:list' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'things:list' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}


{% endblock %}